title: Zirui (Ryan) Zhao
logo: ryan.jpg
description: Senior undergrad in Automation <br/> Xi'an Jiaotong University.<br/> ryan_zzr [at] outlook.com <br/><b><a href="https://github.com/1989Ryan">[GitHub]</a> <a href="https://www.zhihu.com/people/ryan_zzr">[Zhihu]</a> <a href="https://www.ryanzhao.org/CV.pdf">[CV]</a></b>
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
