title: Zirui Zhao Homepage
logo: webwxgetmsgim.jpg
description: Zirui Zhao, Bachelor of Engineering in Automation (EECS) , will graduate in 2020 <br/> Department of Automation Science and Engineering <br/>The School of Electronic and Information Engineering<br/>Xi'an Jiaotong University<br/>No.28 Xianning West Road, Xi'an 710049, P.R.China.<br/>Email: ryan_zzr@outlook.com<br/>Welcome to my [GitHub profile](https://github.com/1989Ryan).<br/>Download my [CV](https://github.com/1989Ryan/README_pictures/raw/master/images/Zirui_Zhao_CV.pdf).<br/>
google_analytics:
theme: jekyll-theme-minimal
